### PR TITLE
Changes for other smart home systems

### PR DESCRIPTION
**Pull request by Bettman66**
e.g. ioBroker

### CODE REVIEW

**Comment by Bettman66** [comment]
@fashberg,
Thank you very much :-)

**Comment by fashberg** [comment]
Hi @Bettman66 !

Please check v1.09-fas 

Frohe Ostern

**Comment by fashberg** [comment]
@Bettman66: Btw: if you have any config-snippets for ioBroker feel free to add to  Readme.md

Tipp: Use https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview

**Comment by Bettman66** [comment]
Frohe Ostern auch dir.
I have a few comments.
deviceOn, schedulesMode are not needed.
ecoMode, locked, mode and target temperature should appear under cmnd. Otherwise everything is great.

Gruß Walter

**Comment by Bettman66** [comment]
**@fashberg**
If you are bored, you can also have the individual schedule objects such as w1h, w1t .... under cmnd, created for reading and writing. The advantage of ioBroker is that you can add the objects directly to the visualization and then read and write them.

**Pull request closed without merging**
